# Generated by Django 4.2.7 on 2026-04-26 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_drop_grado_a_cargo'),
        ('games', '0005_add_5_new_game_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloquePregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enunciado', models.TextField(verbose_name='Enunciado')),
                ('tipo_respuesta', models.CharField(choices=[('opcion_multiple', '⭕ Opción múltiple (una correcta)'), ('casillas', '☑️ Casillas (varias correctas)'), ('parrafo', '✍️ Párrafo libre')], default='opcion_multiple', max_length=20, verbose_name='Tipo de respuesta')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='talleres/preguntas/')),
                ('video_url', models.URLField(blank=True, verbose_name='URL de video (opcional)')),
                ('puntaje_parcial', models.IntegerField(default=10, verbose_name='Puntos de esta pregunta')),
            ],
            options={
                'verbose_name': 'Bloque Pregunta',
                'verbose_name_plural': 'Bloques Pregunta',
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('texto', models.CharField(max_length=300, verbose_name='Texto de la opción')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es correcta?')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='talleres.bloquepregunta')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('puntos_xp', models.IntegerField(default=10, verbose_name='XP al completar')),
                ('huesos_recompensa', models.IntegerField(default=5, verbose_name='Huesos al completar')),
                ('is_active', models.BooleanField(default=False, verbose_name='Publicado')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talleres_creados', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talleres', to='accounts.salon', verbose_name='Salón')),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloqueTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('pregunta', '❓ Pregunta'), ('minijuego', '🎮 Minijuego')], max_length=20)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='talleres.taller')),
            ],
            options={
                'verbose_name': 'Bloque de Taller',
                'verbose_name_plural': 'Bloques de Taller',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='bloquepregunta',
            name='bloque',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloque_pregunta', to='talleres.bloquetaller'),
        ),
        migrations.CreateModel(
            name='BloqueMinijuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bloque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloque_minijuego', to='talleres.bloquetaller')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_taller', to='games.game')),
            ],
            options={
                'verbose_name': 'Bloque Minijuego',
                'verbose_name_plural': 'Bloques Minijuego',
            },
        ),
        migrations.CreateModel(
            name='SesionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completada', models.BooleanField(default=False)),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('huesos_ganados', models.IntegerField(default=0)),
                ('bloque_actual', models.IntegerField(default=0)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_taller', to=settings.AUTH_USER_MODEL)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='talleres.taller')),
            ],
            options={
                'verbose_name': 'Sesión de Taller',
                'verbose_name_plural': 'Sesiones de Taller',
                'unique_together': {('taller', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('texto_respuesta', models.TextField(blank=True)),
                ('es_correcta', models.BooleanField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_taller', to=settings.AUTH_USER_MODEL)),
                ('opciones_elegidas', models.ManyToManyField(blank=True, to='talleres.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='talleres.bloquepregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Estudiante',
                'verbose_name_plural': 'Respuestas de Estudiantes',
                'unique_together': {('estudiante', 'pregunta')},
            },
        ),
    ]
