# Generated by Django 4.2.7 on 2026-04-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquepregunta',
            name='video_archivo',
            field=models.FileField(blank=True, null=True, upload_to='talleres/videos/', verbose_name='Video (.mp4)'),
        ),
        migrations.AlterField(
            model_name='bloquepregunta',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='URL de video (obsoleto)'),
        ),
    ]
