# Generated by Django 6.0.1 on 2026-04-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_vocabularyitem_options_and_more'),
        ('talleres', '0002_bloquepregunta_video_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='categorias_vocabulario',
            field=models.ManyToManyField(blank=True, help_text='Palabras de estas categorías se desbloquearán al completar el taller', related_name='talleres_asociados', to='content.category', verbose_name='Categorías de vocabulario'),
        ),
    ]
