# Generated by Django 6.0.1 on 2026-05-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0003_taller_categorias_vocabulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueminijuego',
            name='instruccion_extra',
            field=models.TextField(blank=True, help_text='Contexto adicional que el profesor puede dar al estudiante antes del juego.', verbose_name='Instrucción extra'),
        ),
        migrations.AddField(
            model_name='sesiontaller',
            name='completada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
