# Generated by Django 6.0.1 on 2026-05-07 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_estudianteprofile_total_estrellas_historia'),
        ('games', '0007_remove_tiendaitem_juego_desbloqueado_and_more'),
        ('talleres', '0004_add_instruccion_extra_completada_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiontaller',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(help_text='Ej: Periodo 1 — Mayo 2026', max_length=120, verbose_name='Título')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha límite')),
                ('meta_historia', models.PositiveIntegerField(default=0, help_text='Número de estrellas de historia que el estudiante debe alcanzar. 0 = sin meta.', verbose_name='Meta de estrellas (Historia)')),
                ('is_activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cerrado', models.BooleanField(default=False, help_text='Un período cerrado congela los resultados.', verbose_name='Cerrado')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='accounts.salon', verbose_name='Salón')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionMinijuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_periodo', to='games.game')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minijuegos_asignados', to='talleres.periodo')),
            ],
            options={
                'verbose_name': 'Minijuego asignado',
                'verbose_name_plural': 'Minijuegos asignados',
                'ordering': ['orden'],
                'unique_together': {('periodo', 'game')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_periodo', to='talleres.taller')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talleres_asignados', to='talleres.periodo')),
            ],
            options={
                'verbose_name': 'Taller asignado',
                'verbose_name_plural': 'Talleres asignados',
                'ordering': ['orden'],
                'unique_together': {('periodo', 'taller')},
            },
        ),
        migrations.CreateModel(
            name='RegistroMinijuegoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('revisado', models.BooleanField(default=False)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='talleres.asignacionminijuego')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_minijuego_periodo', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_minijuego', to='talleres.periodo')),
            ],
            options={
                'verbose_name': 'Registro de minijuego en período',
                'verbose_name_plural': 'Registros de minijuegos en período',
                'unique_together': {('asignacion', 'estudiante')},
            },
        ),
    ]
