# Generated by Django 4.2.7 on 2026-05-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0005_add_periodo_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaestudiante',
            name='dibujo_data',
            field=models.TextField(blank=True, default='', help_text='Data URL base64 del canvas cuando tipo_respuesta es dibujo.', verbose_name='Dibujo (base64 PNG)'),
        ),
        migrations.AlterField(
            model_name='bloquepregunta',
            name='tipo_respuesta',
            field=models.CharField(choices=[('opcion_multiple', '⭕ Opción múltiple (una correcta)'), ('casillas', '☑️ Casillas (varias correctas)'), ('parrafo', '✍️ Párrafo libre'), ('dibujo', '🎨 Dibujo en canvas')], default='opcion_multiple', max_length=20, verbose_name='Tipo de respuesta'),
        ),
    ]
