# Generated by Django 6.0.1 on 2026-05-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0006_add_dibujo_bloque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='salon',
        ),
        migrations.AddField(
            model_name='periodo',
            name='color',
            field=models.CharField(choices=[('morado', '🟣 Morado'), ('azul', '🔵 Azul'), ('verde', '🟢 Verde'), ('naranja', '🟠 Naranja'), ('rosado', '🩷 Rosado'), ('rojo', '🔴 Rojo'), ('amarillo', '🟡 Amarillo'), ('turquesa', '🩵 Turquesa')], default='morado', max_length=20, verbose_name='Color del encabezado'),
        ),
    ]
