# Generated by Django 4.2.7 on 2026-05-06 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_estudianteprofile_total_estrellas_historia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('introduccion', '🎬 Introducción'), ('vocabulario', '📚 Vocabulario'), ('listening', '🎧 Listening'), ('reading', '📖 Reading'), ('writing', '✏️ Writing'), ('minijuego_embed', '🎮 Minijuego'), ('dialogo', '💬 Diálogo'), ('pronunciacion', '🔊 Pronunciación')], max_length=20)),
                ('datos', models.JSONField(default=dict, help_text='Contenido prefabricado según el tipo de actividad')),
                ('puntos_actividad', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion_corta', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('puntos_xp', models.IntegerField(default=10)),
                ('huesos_recompensa', models.IntegerField(default=3)),
                ('tiempo_estimado_minutos', models.IntegerField(default=15)),
                ('icono_emoji', models.CharField(default='📝', max_length=10)),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['seccion__orden', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completada', models.BooleanField(default=False)),
                ('actividad_actual', models.PositiveIntegerField(default=0)),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('estrellas', models.IntegerField(default=0)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('intentos', models.IntegerField(default=0)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_lecciones', to=settings.AUTH_USER_MODEL)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='historia.leccion')),
            ],
            options={
                'verbose_name': 'Progreso de Lección',
                'verbose_name_plural': 'Progresos de Lección',
                'unique_together': {('estudiante', 'leccion')},
            },
        ),
        migrations.CreateModel(
            name='SeccionHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('icono_emoji', models.CharField(default='📖', max_length=10)),
                ('color_hex', models.CharField(default='#6C63FF', max_length=7)),
                ('is_desbloqueada_por_defecto', models.BooleanField(default=False, help_text='Si es True, todos los salones la ven desbloqueada sin acción del profesor.')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('respuesta_dada', models.JSONField(default=dict)),
                ('es_correcta', models.BooleanField(blank=True, null=True)),
                ('respondida_en', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='historia.actividadleccion')),
                ('progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='historia.progresoleccion')),
            ],
            options={
                'verbose_name': 'Respuesta de Actividad',
                'verbose_name_plural': 'Respuestas de Actividad',
                'ordering': ['respondida_en'],
            },
        ),
        migrations.AddField(
            model_name='leccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='historia.seccionhistoria'),
        ),
        migrations.AddField(
            model_name='actividadleccion',
            name='leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='historia.leccion'),
        ),
        migrations.CreateModel(
            name='SeccionDesbloqueada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desbloqueada_en', models.DateTimeField(auto_now_add=True)),
                ('desbloqueada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones_desbloqueadas_por_mi', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones_desbloqueadas', to='accounts.salon')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desbloqueos', to='historia.seccionhistoria')),
            ],
            options={
                'verbose_name': 'Sección Desbloqueada',
                'verbose_name_plural': 'Secciones Desbloqueadas',
                'unique_together': {('seccion', 'salon')},
            },
        ),
    ]
