# Generated by Django 6.0.1 on 2026-04-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_drop_grado_a_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteprofile',
            name='avatar_color',
            field=models.CharField(blank=True, default='#6C63FF', max_length=10),
        ),
        migrations.AddField(
            model_name='estudianteprofile',
            name='avatar_emoji1',
            field=models.CharField(blank=True, default='🐶', max_length=10),
        ),
        migrations.AddField(
            model_name='estudianteprofile',
            name='avatar_emoji2',
            field=models.CharField(blank=True, default='🐱', max_length=10),
        ),
        migrations.AddField(
            model_name='estudianteprofile',
            name='avatar_kitchen_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
