# Generated by Django 4.2.7 on 2026-05-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_estudianteprofile_avatar_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteprofile',
            name='total_estrellas_historia',
            field=models.IntegerField(default=0, verbose_name='Estrellas Modo Historia'),
        ),
    ]
