# Generated by Django 6.0.1 on 2026-05-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_estudianteprofile_total_estrellas_historia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesorprofile',
            name='codigo_clase',
        ),
    ]
