# Generated by Django 6.0.1 on 2026-05-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_numero_identidad_to_numero_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesorprofile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profesores/fotos/', verbose_name='Foto de perfil'),
        ),
    ]
