# Generated by Django 4.2.7 on 2026-04-24 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_tiendaitem_inventarioestudiante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-created_at'], 'verbose_name': 'Obra de Arte', 'verbose_name_plural': 'Obras de Arte'},
        ),
        migrations.AlterModelOptions(
            name='tiendaitem',
            options={'ordering': ['order', 'costo_huesos'], 'verbose_name': 'Item de Tienda', 'verbose_name_plural': 'Items de Tienda'},
        ),
        migrations.AlterField(
            model_name='artwork',
            name='canvas_data',
            field=models.TextField(help_text='Base64 del canvas pintado por el estudiante'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('drag_and_drop', '🖱️ Arrastra y Suelta'), ('word_search', '🔍 Sopa de Letras'), ('puzzle', '🧩 Rompecabezas'), ('audio_matching', '🎵 Juego de Audio'), ('painting', '🎨 Juego de Pintar'), ('memoria', '🃏 Memoria'), ('ahorcado', '🦴 Ahorcado de Milo'), ('quiz', '❓ Quiz Rápido'), ('ordenar_letras', '🔤 Ordenar Letras'), ('globos', '🎈 Globos')], max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_limit',
            field=models.IntegerField(default=120, help_text='Tiempo en segundos (0 = sin límite)'),
        ),
        migrations.AlterField(
            model_name='inventarioestudiante',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='logro',
            name='condicion_valor',
            field=models.IntegerField(default=1, help_text='Valor numérico para desbloquear (ej: 5 juegos)'),
        ),
        migrations.AlterField(
            model_name='paintingword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paintingword',
            name='word',
            field=models.CharField(help_text='Palabra que el estudiante debe dibujar', max_length=100),
        ),
        migrations.AlterField(
            model_name='tiendaitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tiendaitem',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del objeto en la habitación', null=True, upload_to='tienda/'),
        ),
        migrations.AlterField(
            model_name='tiendaitem',
            name='juego_desbloqueado',
            field=models.ForeignKey(blank=True, help_text='Minijuego que se desbloquea al comprar este objeto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desbloqueado_por', to='games.game'),
        ),
        migrations.AlterField(
            model_name='tiendaitem',
            name='posicion_x',
            field=models.IntegerField(default=0, help_text='Posición X en la habitación (%)'),
        ),
        migrations.AlterField(
            model_name='tiendaitem',
            name='posicion_y',
            field=models.IntegerField(default=0, help_text='Posición Y en la habitación (%)'),
        ),
    ]
