# Generated by Django 4.2.7 on 2026-04-26 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_add_5_new_game_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemContenidoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('texto_principal', models.CharField(max_length=200, verbose_name='Texto principal')),
                ('texto_secundario', models.CharField(blank=True, max_length=200, verbose_name='Texto secundario')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='games/contenido/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='games/contenido/audio/')),
                ('es_correcto', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido_custom', to='games.game')),
            ],
            options={
                'verbose_name': 'Item de Contenido',
                'verbose_name_plural': 'Items de Contenido',
                'ordering': ['orden', 'pk'],
            },
        ),
    ]
