# Generated by Django 4.2.7 on 2026-04-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_itemcontenidojuego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiendaitem',
            name='juego_desbloqueado',
        ),
        migrations.AddField(
            model_name='tiendaitem',
            name='juego_entretenimiento',
            field=models.CharField(choices=[('ninguno', '— Sin juego —'), ('flappy_milo', '🐦 Flappy Milo'), ('snake_milo', '🐍 Snake de Milo')], default='ninguno', max_length=20, verbose_name='Juego de entretenimiento'),
        ),
        migrations.AlterField(
            model_name='tiendaitem',
            name='posicion_y',
            field=models.IntegerField(default=0, help_text='Posición Y en la habitación (px sobre el piso)'),
        ),
    ]
