# Generated by Django 6.0.1 on 2026-05-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_tiendaitem_juego_desbloqueado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('drag_and_drop', '🖱️ Arrastra y Suelta'), ('word_search', '🔍 Sopa de Letras'), ('puzzle', '🧩 Rompecabezas'), ('audio_matching', '🎵 Juego de Audio'), ('painting', '🎨 Juego de Pintar'), ('memoria', '🃏 Memoria'), ('ahorcado', '🦴 Ahorcado de Milo'), ('quiz', '❓ Quiz Rápido'), ('ordenar_letras', '🔤 Ordenar Letras'), ('globos', '🎈 Globos'), ('atrapa_palabra', '🎯 Atrapa la Palabra')], max_length=30),
        ),
    ]
