# Generated by Django 6.0.1 on 2026-05-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_game_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemContenidoJuego',
        ),
    ]
