# Generated by Django 6.0.1 on 2026-05-14 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_remove_itemcontenidojuego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('drag_and_drop', '🖱️ Arrastra y Suelta'), ('word_search', '🔍 Sopa de Letras'), ('puzzle', '🧩 Rompecabezas'), ('audio_matching', '🎵 Juego de Audio'), ('painting', '🎨 Juego de Pintar'), ('memoria', '🃏 Memoria'), ('ahorcado', '🦴 Ahorcado de Milo'), ('quiz', '❓ Quiz Rápido'), ('ordenar_letras', '🔤 Ordenar Letras'), ('globos', '🎈 Globos')], max_length=30),
        ),
        migrations.CreateModel(
            name='PuzzleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Nombre que aparece sobre el rompecabezas', max_length=100)),
                ('image', models.ImageField(upload_to='games/puzzle/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_images', to='games.game')),
            ],
            options={
                'verbose_name': 'Imagen de Rompecabezas',
                'verbose_name_plural': 'Imágenes de Rompecabezas',
                'ordering': ['order', 'id'],
            },
        ),
    ]
