# Generated by Django 6.0.1 on 2026-05-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_remove_game_points_reward_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('drag_and_drop', '🖱️ Arrastra y Suelta'), ('word_search', '🔍 Sopa de Letras'), ('puzzle', '🧩 Rompecabezas'), ('audio_matching', '🎵 Juego de Audio'), ('painting', '🎨 Juego de Pintar'), ('memoria', '🃏 Memoria'), ('ahorcado', '🦴 Ahorcado de Milo'), ('quiz', '❓ Quiz Rápido'), ('ordenar_letras', '🔤 Ordenar Letras'), ('globos', '🎈 Globos'), ('comparacion', '🖼️ Comparación')], max_length=30),
        ),
    ]
