# Generated by Django 4.2.7 on 2026-05-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_add_comparacion_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioestudiante',
            name='escala',
            field=models.FloatField(default=1.0, help_text='Escala del objeto (1.0 = normal)'),
        ),
        migrations.AddField(
            model_name='inventarioestudiante',
            name='pos_x',
            field=models.FloatField(default=50.0, help_text='Posición X en % del ancho del cuarto'),
        ),
        migrations.AddField(
            model_name='inventarioestudiante',
            name='pos_y',
            field=models.FloatField(default=10.0, help_text='Posición Y en px sobre el piso'),
        ),
    ]
