# Generated by Django 6.0.1 on 2026-05-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_memoriacard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('drag_and_drop', '🖱️ Arrastra y Suelta'), ('word_search', '🔍 Sopa de Letras'), ('puzzle', '🧩 Rompecabezas'), ('audio_matching', '🎵 Juego de Audio'), ('painting', '🎨 Juego de Pintar'), ('memoria', '🃏 Memoria'), ('ahorcado', '🦴 Ahorcado de Milo'), ('globos', '🎈 Globos'), ('comparacion', '🖼️ Comparación')], max_length=30),
        ),
        migrations.AlterField(
            model_name='memoriacard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wordsearchword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
