# Generated by Django 6.0.1 on 2026-06-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_populate_tienda_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('drag_and_drop', '🔗 Conectar imágenes con palabras'), ('word_search', '🔍 Sopa de Letras'), ('puzzle', '🧩 Rompecabezas'), ('audio_matching', '🎵 Juego de Audio'), ('painting', '🎨 Juego de Pintar'), ('memoria', '🃏 Memoria'), ('ahorcado', '🦴 Ahorcado de Milo'), ('globos', '🎈 Globos'), ('comparacion', '🖼️ Comparación')], max_length=30),
        ),
    ]
