# Generated by Django 4.2.7 on 2026-04-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='vocabularyitem',
            options={'ordering': ['word_en'], 'verbose_name': 'Vocabulario', 'verbose_name_plural': 'Vocabulario'},
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#6C63FF', help_text='Color HEX para la tarjeta (ej: #FF6B6B)', max_length=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('🐾', 'Animales'), ('🎨', 'Colores'), ('🔢', 'Números'), ('🍎', 'Frutas'), ('🏠', 'Casa'), ('🏫', 'Escuela'), ('👗', 'Ropa'), ('🌦️', 'Clima'), ('👨\u200d👩\u200d👧', 'Familia'), ('🚗', 'Transporte'), ('🌿', 'Naturaleza'), ('🍔', 'Comida')], default='🐾', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre (Español)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Nombre (Inglés)'),
        ),
        migrations.AlterField(
            model_name='vocabularyitem',
            name='audio',
            field=models.FileField(blank=True, help_text='Archivo .mp3 con la pronunciación en inglés', null=True, upload_to='vocabulary/audio/'),
        ),
        migrations.AlterField(
            model_name='vocabularyitem',
            name='hint',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pista o contexto'),
        ),
        migrations.AlterField(
            model_name='vocabularyitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vocabularyitem',
            name='word_en',
            field=models.CharField(max_length=100, verbose_name='Word in English'),
        ),
        migrations.AlterField(
            model_name='vocabularyitem',
            name='word_es',
            field=models.CharField(max_length=100, verbose_name='Palabra en Español'),
        ),
    ]
