# Generated by Django 4.2.7 on 2026-04-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_category_options_alter_vocabularyitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='🐾', max_length=10),
        ),
    ]
