# Generated by Django 6.0.1 on 2026-04-30 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_category_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocabularyitem',
            options={'ordering': ['orden', 'word_en'], 'verbose_name': 'Vocabulario', 'verbose_name_plural': 'Vocabulario'},
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='descripcion_es',
            field=models.TextField(blank=True, help_text='Definición sencilla en español para el estudiante', verbose_name='Descripción en español'),
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='is_unlocked_by_default',
            field=models.BooleanField(default=False, help_text='True = visible para todos los estudiantes sin completar nada', verbose_name='Desbloqueada por defecto'),
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden dentro de categoría'),
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='pronunciacion_es',
            field=models.CharField(blank=True, help_text='Ej: "dog" se pronuncia "dag"', max_length=150, verbose_name='Pronunciación aproximada'),
        ),
        migrations.CreateModel(
            name='HitoVocabulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabras_cantidad', models.IntegerField(verbose_name='Palabras al alcanzar el hito')),
                ('huesos_ganados', models.IntegerField(verbose_name='Huesos otorgados')),
                ('entregado_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos_vocabulario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hito de Vocabulario',
                'verbose_name_plural': 'Hitos de Vocabulario',
                'ordering': ['palabras_cantidad'],
                'unique_together': {('estudiante', 'palabras_cantidad')},
            },
        ),
        migrations.CreateModel(
            name='VocabularioDesbloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desbloqueado_en', models.DateTimeField(auto_now_add=True)),
                ('fuente', models.CharField(choices=[('inicial', 'Inicial'), ('taller', 'Taller'), ('minijuego', 'Minijuego')], default='inicial', max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulario_desbloqueado', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desbloqueado_por', to='content.vocabularyitem')),
            ],
            options={
                'verbose_name': 'Vocabulario Desbloqueado',
                'verbose_name_plural': 'Vocabulario Desbloqueado',
                'ordering': ['-desbloqueado_en'],
                'unique_together': {('estudiante', 'item')},
            },
        ),
    ]
