# Generated by Django 6.0.1 on 2026-05-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_vocabularyitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyitem',
            name='emoji',
            field=models.CharField(blank=True, default='', help_text='Emoji individual de la palabra (ej: 🐕 para Dog)', max_length=10, verbose_name='Emoji representativo'),
        ),
    ]
