# Generated by Django 4.2.7 on 2026-05-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_add_emoji_to_vocabularyitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulariodesbloqueado',
            name='fuente',
            field=models.CharField(choices=[('inicial', 'Inicial'), ('taller', 'Taller'), ('minijuego', 'Minijuego'), ('historia', 'Modo Historia')], default='inicial', max_length=20),
        ),
    ]
