# Generated by Django 6.0.1 on 2026-05-13 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=10)),
                ('contenido', models.TextField()),
                ('modo', models.CharField(choices=[('planeacion', 'Planeación'), ('analisis', 'Análisis')], max_length=20)),
                ('motor_usado', models.CharField(blank=True, choices=[('gemini', 'Gemini'), ('groq', 'Groq'), ('error', 'Error')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_asistente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['created_at'],
            },
        ),
    ]
