# Generated by Django 6.0.1 on 2026-05-28 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('planeacion', 'Asistente de Planeación (chat)'), ('correccion', 'Corrección de Milo (estudiante)'), ('generar_taller', 'Generador de Talleres con IA'), ('insights_periodo', 'Insights de Período (análisis)')], max_length=50, unique=True, verbose_name='Identificador del prompt')),
                ('system', models.TextField(verbose_name='System Prompt')),
                ('activo', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, help_text='Descripción del propósito, cambios realizados, etc.', verbose_name='Notas internas')),
            ],
            options={
                'verbose_name': 'Prompt Template',
                'verbose_name_plural': 'Prompt Templates',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LlamadaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(choices=[('gemini', 'Gemini'), ('groq', 'Groq'), ('cache', 'Cache (hit)'), ('sin_datos', 'Sin datos'), ('error', 'Error')], max_length=10)),
                ('proposito', models.CharField(blank=True, help_text='Ej: chat_planeacion, milo_correccion, generar_taller', max_length=80)),
                ('latencia_ms', models.PositiveIntegerField(default=0, verbose_name='Latencia (ms)')),
                ('exito', models.BooleanField(default=True)),
                ('cache_hit', models.BooleanField(default=False, verbose_name='Respondido desde caché')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Llamada IA',
                'verbose_name_plural': 'Llamadas IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
